"""initial tables

Revision ID: 16108349ded3
Revises: 469657286114
Create Date: 2025-09-27 13:49:30.671566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16108349ded3'
down_revision = '469657286114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
