"""initial tables

Revision ID: 469657286114
Revises: c14822b1c34d
Create Date: 2025-09-27 13:39:00.524805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469657286114'
down_revision = 'c14822b1c34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
